import type { CSSProperties } from "react";

// ----------------------------------------------------
// UI Styles (TradingView Dark Theme)
// ----------------------------------------------------
export const styles: Record<string, CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    width: "100vw",
    backgroundColor: "#131722",
    overflow: "hidden",
  },
  header: {
    height: "56px",
    backgroundColor: "#111822",
    borderBottom: "1px solid #263244",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 16px",
    zIndex: 10,
  },
  analysisModeSwitch: {
    display: "flex",
    alignItems: "center",
    height: "40px",
    padding: "4px",
    gap: "4px",
    backgroundColor: "#0b1018",
    border: "1px solid #334155",
    borderRadius: "7px",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.03)",
  },
  analysisModeButton: {
    height: "30px",
    padding: "0 12px",
    border: "1px solid transparent",
    borderRadius: "5px",
    backgroundColor: "transparent",
    color: "#9aa7b8",
    fontSize: "12px",
    fontWeight: 700,
    whiteSpace: "nowrap",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "7px",
    transition: "background-color 160ms ease, color 160ms ease, border-color 160ms ease",
  },
  ruleModeButtonActive: {
    backgroundColor: "rgba(45, 212, 191, 0.16)",
    borderColor: "rgba(45, 212, 191, 0.58)",
    color: "#5eead4",
  },
  aiModeButtonActive: {
    backgroundColor: "rgba(251, 191, 36, 0.14)",
    borderColor: "rgba(251, 191, 36, 0.58)",
    color: "#fcd34d",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  logoIcon: {
    fontSize: "20px",
  },
  logoText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: "16px",
    letterSpacing: 0,
  },
  disclaimer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    gap: "7px",
    padding: "6px 16px",
    borderTop: "1px solid #2a2e39",
    backgroundColor: "#11151f",
    color: "#8b93a7",
    fontSize: "11px",
    lineHeight: 1.45,
  },
  searchContainer: {
    position: "relative",
    width: "350px",
    display: "flex",
    alignItems: "center",
  },
  searchIcon: {
    position: "absolute",
    left: "12px",
    color: "#787b86",
  },
  searchInput: {
    width: "100%",
    backgroundColor: "#2a2e39",
    border: "1px solid #363c4e",
    borderRadius: "4px",
    color: "#ffffff",
    padding: "8px 38px 8px 36px",
    fontSize: "13px",
    outline: "none",
    transition: "border-color 0.2s",
  },
  addWatchlistBtn: {
    position: "absolute",
    right: "8px",
    backgroundColor: "transparent",
    border: "none",
    color: "#787b86",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  suggestionsDropdown: {
    position: "absolute",
    top: "38px",
    left: 0,
    width: "100%",
    backgroundColor: "#1c2030",
    border: "1px solid #2a2e39",
    borderRadius: "4px",
    boxShadow: "0 8px 16px rgba(0,0,0,0.5)",
    maxHeight: "300px",
    overflowY: "auto",
    zIndex: 100,
  },
  suggestionItem: {
    padding: "10px 12px",
    cursor: "pointer",
    borderBottom: "1px solid #2a2e39",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "13px",
    color: "#d1d4dc",
    transition: "background-color 0.15s",
  },
  sSymbol: {
    fontWeight: "bold",
    color: "#ffffff",
    width: "80px",
  },
  sName: {
    flex: 1,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    paddingRight: "8px",
    color: "#787b86",
  },
  sExchange: {
    fontSize: "11px",
    color: "#2962ff",
    backgroundColor: "rgba(41,98,255,0.1)",
    padding: "2px 6px",
    borderRadius: "3px",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  langSelectContainer: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#2a2e39",
    borderRadius: "4px",
    padding: "0 8px 0 10px",
    gap: "6px",
    height: "28px",
  },
  langSelect: {
    backgroundColor: "transparent",
    border: "none",
    color: "#d1d4dc",
    fontSize: "12px",
    fontWeight: 600,
    outline: "none",
    cursor: "pointer",
  },
  settingsBtn: {
    backgroundColor: "#2a2e39",
    border: "none",
    color: "#d1d4dc",
    padding: "6px 12px",
    fontSize: "12px",
    fontWeight: 600,
    borderRadius: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    transition: "background 0.2s",
  },
  refreshBtn: {
    backgroundColor: "transparent",
    border: "none",
    color: "#787b86",
    cursor: "pointer",
  },
  body: {
    display: "flex",
    flex: 1,
    overflow: "hidden",
  },
  sidebar: {
    width: "220px",
    borderRight: "1px solid #2a2e39",
    backgroundColor: "#131722",
    display: "flex",
    flexDirection: "column",
  },
  sidebarHeader: {
    fontSize: "11px",
    color: "#787b86",
    fontWeight: "bold",
    letterSpacing: "1px",
    padding: "16px 12px 8px 12px",
    borderBottom: "1px solid #1c2030",
  },
  watchlistContainer: {
    flex: 1,
    overflowY: "auto",
  },
  watchItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 12px",
    cursor: "pointer",
    borderBottom: "1px solid #1c2030",
    transition: "background-color 0.2s",
  },
  watchItemLeft: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    flex: 1,
  },
  watchSymbol: {
    fontWeight: "bold",
    color: "#ffffff",
    fontSize: "13px",
  },
  watchItemRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    position: "relative",
    paddingRight: "20px",
    flexShrink: 0,
  },
  watchPrice: {
    fontSize: "13px",
    color: "#ffffff",
  },
  watchChange: {
    fontSize: "11px",
    fontWeight: "bold",
    marginTop: "2px",
  },
  removeWatchBtn: {
    position: "absolute",
    right: 0,
    top: "10px",
    backgroundColor: "transparent",
    border: "none",
    color: "#787b86",
    cursor: "pointer",
    opacity: 0.5,
  },
  watchLoading: {
    fontSize: "12px",
    color: "#787b86",
  },
  main: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
    position: "relative",
    minHeight: 0,
  },
  welcomeContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    height: "100%",
    backgroundColor: "#0b1018",
  },
  dashboardGrid: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100%",
  },
  topRow: {
    backgroundColor: "#1c2030",
    borderBottom: "1px solid #2a2e39",
    padding: "16px 20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "20px",
    flexWrap: "wrap",
  },
  watchTimestamp: {
    color: "#787b86",
    fontSize: "12px",
    lineHeight: 1.35,
    marginTop: "3px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  statsContainer: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#171b26",
    border: "1px solid #2a2e39",
    borderRadius: "8px",
    padding: "12px 24px",
    gap: "24px",
    flexWrap: "wrap",
    justifyContent: "center",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.2)",
  },
  statItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  statLabel: {
    fontSize: "12.5px",
    color: "#787b86",
    marginBottom: "6px",
    textTransform: "uppercase",
  },
  statValue: {
    fontSize: "18.5px",
    fontWeight: "bold",
    color: "#d1d4dc",
    display: "flex",
    alignItems: "baseline",
    gap: "4px",
  },
  statDivider: {
    width: "1px",
    height: "36px",
    backgroundColor: "#2a2e39",
  },
  scoreBreakdownRow: {
    display: "flex",
    gap: "10px",
    marginTop: "6px",
    color: "#787b86",
    fontSize: "11px",
    lineHeight: 1.35,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  scenarioRow: {
    display: "flex",
    gap: "6px",
    marginTop: "6px",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  scenarioBadge: {
    border: "1px solid #363c4e",
    borderRadius: "4px",
    padding: "2px 5px",
    fontSize: "10.5px",
    lineHeight: 1.2,
    whiteSpace: "nowrap",
  },
  dataStatus: {
    color: "#787b86",
    fontSize: "10.5px",
    lineHeight: 1.3,
    maxWidth: "260px",
    overflowWrap: "anywhere",
  },
  leftColumn: {
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid #2a2e39",
    overflow: "hidden",
    height: "100%",
    minHeight: 0,
  },
  rightColumn: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#171b26",
    overflow: "hidden",
    height: "100%",
    minHeight: 0,
  },
  summaryCard: {
    backgroundColor: "#171b26",
    borderBottom: "1px solid #2a2e39",
    display: "flex",
    flexDirection: "column",
    flex: "0 1 auto",
    maxHeight: "32vh",
    minHeight: "104px",
    overflow: "hidden",
  },
  recommendationCard: {
    backgroundColor: "#171b26",
    borderBottom: "1px solid #2a2e39",
    display: "flex",
    flexDirection: "column",
    flex: "0 1 auto",
    maxHeight: "32vh",
    minHeight: "104px",
    overflow: "hidden",
  },
  cardHeader: {
    backgroundColor: "#1c2030",
    borderBottom: "1px solid #2a2e39",
    padding: "8px 12px",
    fontSize: "14px",
    fontWeight: "bold",
    color: "#ffffff",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardBodyAuto: {
    flex: 1,
    padding: "16px 20px",
    overflowY: "visible",
    fontSize: "14.5px",
    lineHeight: "1.6",
    color: "#d1d4dc",
  },
  cardBodyAutoScroll: {
    flex: 1,
    padding: "12px 16px",
    overflowY: "auto",
    minHeight: 0,
    fontSize: "14.5px",
    lineHeight: "1.6",
    color: "#d1d4dc",
  },
  tickerInfo: {
    display: "flex",
    alignItems: "baseline",
    gap: "12px",
    flexWrap: "wrap",
  },
  tickerName: {
    fontSize: "26px",
    fontWeight: "bold",
    color: "#ffffff",
  },
  tickerSymbol: {
    fontSize: "15px",
    color: "#787b86",
  },
  priceContainer: {
    display: "flex",
    alignItems: "baseline",
    gap: "8px",
  },
  currentPrice: {
    fontSize: "26px",
    fontWeight: "bold",
    color: "#ffffff",
  },
  priceChange: {
    fontSize: "15px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  scoreCard: {
    background: "linear-gradient(135deg, #1e293b 0%, #0f172a 100%)",
    border: "1px solid #2962ff",
    borderRadius: "6px",
    padding: "10px 16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    boxShadow: "0 4px 12px rgba(41, 98, 255, 0.15)",
  },
  scoreVal: {
    fontSize: "26px",
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: "4px",
  },
  scoreSub: {
    fontSize: "11px",
    color: "#787b86",
    marginTop: "4px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  workspaceGrid: {
    display: "grid",
    gridTemplateColumns: "3fr 2fr",
    flex: 1,
    minHeight: "620px",
    overflow: "hidden",
  },
  chartArea: {
    display: "flex",
    flexDirection: "column",
    overflow: "auto",
    flex: 1,
    minHeight: "460px",
  },
  chartSelector: {
    backgroundColor: "#1c2030",
    borderBottom: "1px solid #2a2e39",
    padding: "6px 12px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  periodBtn: {
    border: "none",
    color: "#ffffff",
    padding: "4px 10px",
    fontSize: "12px",
    borderRadius: "3px",
    cursor: "pointer",
    fontWeight: 600,
  },
  reportArea: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#171b26",
    overflow: "hidden",
    flex: 1,
  },
  reportHeader: {
    backgroundColor: "#1c2030",
    borderBottom: "1px solid #2a2e39",
    padding: "10px 16px",
    fontSize: "14px",
    fontWeight: "bold",
    color: "#ffffff",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  llmBadge: {
    fontSize: "11px",
    color: "#34a853",
    backgroundColor: "rgba(52,168,83,0.15)",
    padding: "2px 6px",
    borderRadius: "10px",
    fontWeight: "bold",
  },
  ruleBadge: {
    fontSize: "11px",
    color: "#fbbf24",
    backgroundColor: "rgba(251,191,36,0.15)",
    padding: "2px 6px",
    borderRadius: "10px",
    fontWeight: "bold",
  },
  reportScroll: {
    flex: 1,
    padding: "16px 20px",
    overflowY: "auto",
    lineHeight: "1.65",
    fontSize: "14.5px",
    color: "#d1d4dc",
  },

  // Markdown rendering styles
  mdH2: {
    fontSize: "16.5px",
    fontWeight: "bold",
    color: "#ffffff",
    borderLeft: "3px solid #2962ff",
    paddingLeft: "8px",
    marginTop: "18px",
    marginBottom: "10px",
  },
  mdH3: {
    fontSize: "14.5px",
    fontWeight: "bold",
    color: "#ffffff",
    marginTop: "12px",
    marginBottom: "6px",
  },
  mdUl: {
    paddingLeft: "16px",
    marginBottom: "6px",
  },
  mdLi: {
    fontSize: "14.5px",
    marginBottom: "4px",
    color: "#d1d4dc",
  },
  mdP: {
    fontSize: "14.5px",
    marginBottom: "10px",
    color: "#b2b5be",
  },
  mdHr: {
    border: "none",
    borderTop: "1px solid #2a2e39",
    margin: "16px 0",
  },
  mockWarningBanner: {
    backgroundColor: "#fbbf24",
    color: "#0f172a",
    padding: "8px 16px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "13.5px",
    fontWeight: 500,
    zIndex: 9,
    boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
  },
  closeWarningBtn: {
    backgroundColor: "transparent",
    border: "none",
    color: "#0f172a",
    fontSize: "16px",
    cursor: "pointer",
    fontWeight: "bold",
    padding: "0 4px",
    display: "flex",
    alignItems: "center",
  },
  eastMoneyBadge: {
    fontSize: "11px",
    color: "#089981",
    backgroundColor: "rgba(8,153,129,0.15)",
    padding: "2px 6px",
    borderRadius: "10px",
    fontWeight: "bold",
    marginLeft: "8px",
    display: "inline-block",
  },
  tonghuashunBadge: {
    fontSize: "11px",
    color: "#f59e0b",
    backgroundColor: "rgba(245,158,11,0.15)",
    padding: "2px 6px",
    borderRadius: "10px",
    fontWeight: "bold",
    marginLeft: "8px",
    display: "inline-block",
  },
  yahooBadge: {
    fontSize: "11px",
    color: "#2962ff",
    backgroundColor: "rgba(41,98,255,0.15)",
    padding: "2px 6px",
    borderRadius: "10px",
    fontWeight: "bold",
    marginLeft: "8px",
    display: "inline-block",
  },
  kabutanBadge: {
    fontSize: "11px",
    color: "#38bdf8",
    backgroundColor: "rgba(56,189,248,0.15)",
    padding: "2px 6px",
    borderRadius: "10px",
    fontWeight: "bold",
    marginLeft: "8px",
    display: "inline-block",
  },
  providerBadge: {
    fontSize: "11px",
    color: "#a78bfa",
    backgroundColor: "rgba(167,139,250,0.15)",
    padding: "2px 6px",
    borderRadius: "10px",
    fontWeight: "bold",
    marginLeft: "8px",
    display: "inline-block",
  },
  mockBadge: {
    fontSize: "11px",
    color: "#fbbf24",
    backgroundColor: "rgba(251,191,36,0.15)",
    padding: "2px 6px",
    borderRadius: "10px",
    fontWeight: "bold",
    marginLeft: "8px",
    display: "inline-block",
  },
  welcomeContent: {
    width: "min(100%, 980px)",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  welcomeHero: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    textAlign: "left",
    maxWidth: "760px",
    gap: "8px",
    paddingTop: "4px",
  },
  welcomeEyebrow: {
    color: "#5eead4",
    fontSize: "12px",
    fontWeight: 800,
    textTransform: "uppercase",
  },
  welcomeTitle: {
    color: "#f8fafc",
    fontSize: "34px",
    lineHeight: 1.2,
    fontWeight: 780,
  },
  welcomeSubtitle: {
    color: "#9aa7b8",
    fontSize: "15px",
    lineHeight: 1.65,
    maxWidth: "720px",
  },
  welcomeModeSection: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  welcomeSectionHeading: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: "16px",
  },
  welcomeSectionTitle: {
    color: "#f8fafc",
    fontSize: "18px",
    lineHeight: 1.35,
    fontWeight: 750,
  },
  welcomeSectionSubtitle: {
    color: "#8b98aa",
    fontSize: "13px",
    lineHeight: 1.55,
    marginTop: "5px",
  },
  sharedDataBadge: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    color: "#b8c4d3",
    border: "1px solid #334155",
    backgroundColor: "#111822",
    borderRadius: "6px",
    padding: "7px 10px",
    fontSize: "12px",
    fontWeight: 650,
    whiteSpace: "nowrap",
  },
  welcomeModeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "14px",
  },
  welcomeModeCard: {
    width: "100%",
    minHeight: "250px",
    border: "1px solid",
    borderRadius: "8px",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    textAlign: "left",
    color: "#d8e1ea",
    cursor: "pointer",
    transition: "background-color 160ms ease, border-color 160ms ease, box-shadow 160ms ease",
  },
  modeCardTop: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    marginBottom: "16px",
  },
  modeIcon: {
    width: "42px",
    height: "42px",
    borderRadius: "7px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  modeSelectionState: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    fontSize: "12px",
    fontWeight: 750,
  },
  modeTitle: {
    color: "#f8fafc",
    fontSize: "17px",
    lineHeight: 1.35,
    marginBottom: "7px",
  },
  modeSummary: {
    color: "#a6b1c1",
    fontSize: "13px",
    lineHeight: 1.55,
    minHeight: "41px",
  },
  modePoints: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginTop: "15px",
  },
  modePoint: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    color: "#cbd5e1",
    fontSize: "12.5px",
    lineHeight: 1.45,
  },
  modeBestFor: {
    marginTop: "auto",
    paddingTop: "14px",
    borderTop: "1px solid",
    width: "100%",
    color: "#94a3b8",
    fontSize: "12px",
    lineHeight: 1.45,
  },
  welcomeInfoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "14px",
  },
  objectivePanel: {
    display: "flex",
    alignItems: "flex-start",
    gap: "12px",
    padding: "16px 18px",
    border: "1px solid #263244",
    borderRadius: "8px",
    backgroundColor: "#101720",
  },
  riskPanel: {
    display: "flex",
    alignItems: "flex-start",
    gap: "12px",
    padding: "16px 18px",
    border: "1px solid rgba(251, 191, 36, 0.32)",
    borderRadius: "8px",
    backgroundColor: "rgba(251, 191, 36, 0.055)",
  },
  infoPanelTitle: {
    color: "#e5edf5",
    fontSize: "13.5px",
    lineHeight: 1.35,
    fontWeight: 750,
    marginBottom: "5px",
  },
  infoPanelText: {
    color: "#94a3b8",
    fontSize: "12.5px",
    lineHeight: 1.55,
  },
  welcomeGuide: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    paddingTop: "4px",
  },
  guideHeading: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: "20px",
  },
  guideSteps: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "1px",
    overflow: "hidden",
    border: "1px solid #263244",
    borderRadius: "7px",
    backgroundColor: "#263244",
  },
  guideStep: {
    minHeight: "152px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    backgroundColor: "#111822",
  },
  guideStepMarker: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "16px",
  },
  guideStepNumber: {
    color: "#0b1018",
    backgroundColor: "#2dd4bf",
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    fontWeight: 800,
  },
  guideStepTitle: {
    color: "#e5edf5",
    fontSize: "13.5px",
    lineHeight: 1.4,
    marginBottom: "7px",
  },
  guideStepDesc: {
    color: "#8b98aa",
    fontSize: "12px",
    lineHeight: 1.55,
  },
  welcomeQuickStart: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "20px",
    paddingTop: "4px",
  },
  quickStartTitle: {
    fontSize: "14px",
    color: "#e5edf5",
    fontWeight: 750,
  },
  quickStartDesc: {
    fontSize: "12px",
    color: "#768499",
    lineHeight: 1.45,
    marginTop: "4px",
  },
  quickStartBadges: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  quickBadgeBtn: {
    backgroundColor: "#172230",
    border: "1px solid #334155",
    color: "#d9e4ee",
    padding: "8px 14px",
    fontSize: "12.5px",
    fontWeight: "bold",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "background-color 160ms ease, border-color 160ms ease",
  },
};
